version: '3.7'

services:
  web:
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: "python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=recipe_app
      - DB_USER=postgres
      - DB_PASSWORD=password123
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=recipe_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123